apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace: etudiant23-ns
spec:
  selector:
    app: todo-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080